#### general settings
name: HDR2IR_UNet_ours
use_tb_logger: true  # tensorboard logger
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: RGBTHDRDataset_training
    mode: HDR2IR
    hdr_dir: ./dataset/hdr_reduced_size
    t_dir: ./dataset/infrared
    index_path: ./dataset/trainingset.txt
    do_transform: true

    use_shuffle: true
    n_workers: 5
    batch_size: 16
    GT_size: 256

  val:
    name: RGBTHDRDataset_test
    mode: HDR2IR
    hdr_dir: ./dataset/hdr_reduced_size
    t_dir: ./dataset/infrared
    index_path: ./dataset/testset.txt
    GT_size: &dataset_size 256
    n_workers: 5

#### network structures
network_G:
  which_model_G: HDR2IR_Feature_Ours
  in_nc: 3
  out_nc: 1
  size: *dataset_size

#### path
path:
  root: ./
#  pretrain_model_G: ./experiments/
  strict_load: false
#  resume_state: ./experiments/Feature_originalUNet/training_state/34500.state

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 4e-5
  beta1: 0.9
  beta2: 0.99
  nepoch: 200
  warmup_iter: 1000  # no warm up
  weight_decay_G: !!float 1e-8

  lr_scheme: MultiStepLR # MultiStepLR | CosineAnnealingLR_Restart
  lr_steps: [60000, 120000, 180000, 240000]
  lr_gamma: 0.5

  pixel_criterion: l1 # l1 | l2 | tanh_l1 | tanh_l2 | lab_L1
  pixel_weight: 1.0
  similarity_weight: !!float 1e-2
  ganloss_weight: !!float 1e-5
  perceptual_loss_weight: 1.0

  manual_seed: 10
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
